### ISSUE TITLE
Home page promotional lists messed up

### ISSUE THREAD

**Issue by wendy-guan** [cga-harvard/CAMP#11]
1.	On CAMP home page, there are three lists by design: 
a.	Top – Profiled maps (hand picked by the admin)
b.	Middle - Hottest maps (automatically filtered, maps with the most hits)
c.	Bottom – Latest maps (automatically filtered, maps most recently created)
Right now they became all the same (Latest maps). Please restore the original design.

**Comment by capooti** [comment]
Thanks for reporting, will fix this as well (should be easy)

**Comment by wendy-guan** [comment]
Prof. Xu is anxious about this.

**Comment by capooti** [comment]
@wendy-guan this should now be fixed. The issue was caused from javascript code developed by CAMP team which was replacing the images from API (which were and are correct) with fixed thumbnails. I now commented it out and it is working as it should:
https://github.com/cga-harvard/CAMP/commit/e0fc49eb1ffd92521ed96b2ec244d611570bf570
