### ISSUE TITLE
Uploading geojson layer and new layer is not displayed

### ISSUE THREAD

**Issue by blewis** [cga-harvard/CAMP#15]
Uploading geojson and layer not displayed in layer page
![image](https://user-images.githubusercontent.com/812849/64458548-a364c080-d0c3-11e9-917a-6187c85f72f5.png)

Will send geojson file by email.

**Comment by blewis** [comment]
This seems to be true with all files.  Perhaps geoserver is down?

**Comment by capooti** [comment]
Thanks for reporting. This is the same error we had a few days ago. I fixed it last week by setting DELAYED_SECURITY_SIGNALS to False (it was set to True by GeoSolutions after their work). I was hoping that with latest changes we could set it to True again but is not the case. Setting it to False again - and working again now.
Let's keep it open for now, as I want to use that setting with True. The problem here is that there must be a problem with that setting when using the REST uploader (we use that for GeoJson layers)
